create sequence  IF NOT EXISTS hibernate_sequence START with 1 INCREMENT BY 1;

create TABLE api_description (
  id UUID NOT NULL,
   api_title VARCHAR(255),
   status BOOLEAN,
   created_at TIMESTAMP with time zone NOT NULL,
   updated_at TIMESTAMP with time zone NOT NULL,
   updated_by VARCHAR(255),
   CONSTRAINT pk_api_description PRIMARY KEY (id)
);

alter table todo drop COLUMN id;

alter table todo add id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;